# 公開するページのURL
baseURL = "https://assault1892.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "/home/assault"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "あさると"
    bio = "PAYDAY2とVRChatをあそんでます"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Assault"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#6495ed"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "SzlyNe_"
  github = "Assault1892"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]