# 公開するページのURL
baseURL = "https://assault1892.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
summaryLength = 0
enableRobotsTXT = true

# ブログのタイトル
title = "/home/assault"
theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "あさると"
    bio = "PAYDAY2とVRChatを主に遊んでいます / フロントエンドをたまに触る"
    avatar = "img/avatar.png"

[Params]
    description = "なんか色々書いてます 基本的に翻訳多め たまに何かしらのレビューっぽい物を書く"
    customCSS = ["css/custom.css"]
    copyright = "Assault"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#6495ed"

[Params.logo]
  logo = false
  title = "/home/assault"
  subtitle = "雑記、翻訳多め | 気が向いた時にレビューっぽい物を書きます"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "SzlyNe_"
  github = "Assault1892"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["recent", "categories", "taglist", "social"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true